name: forest_focus
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sleek_circular_slider: ^2.1.0 #圆形进度条
  syncfusion_flutter_gauges: ^33.2.13+1 #圆形进度条
  flame: ^1.35.0 #flutter的sprireKit
  provider: ^6.1.5
  shared_preferences: ^2.2.3 #持久化的
  path_provider: ^2.1.5 #返回存储路径的把
  sqflite: ^2.4.2
  google_fonts: ^6.2.1
  fl_chart: ^1.0.0
#  flutter_local_notifications: ^19.4.0
#  timezone: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/images/
    - assets/images/flower/
    - assets/images/grass/
    - assets/images/mushroom/
    - assets/images/shrub/
    - assets/images/tree/
    - assets/ui/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"